language: minimal

services:
  - docker

before_install:
  - git clone https://github.com/evmiguel/git-tag-api.git
  - cd git-tag-api

before_script:
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

script:
  - aws s3 cp s3://evmiguel/.env ./
  - docker build -t tag-api-image .
  - docker run -d -p 3000:3000 tag-api-image
  - sleep 5
  - curl http://localhost:3000
  - docker stop $(docker ps -q)  # Stop all running containers