language: minimal

services:
  - docker

before_install:
  - git clone https://github.com/evmiguel/git-tag-api.git
  - cd git-tag-api

script:
  - docker build -t tag-api-image .
  - docker run -d -p 3000:3000 tag-api-image
  - sleep 5
  - curl http://localhost:3000
  - docker stop $(docker ps -q)  # Stop all running containers