
- name: Ensure Docker is installed
  hosts: all
  become: true

  tasks:
    - name: Check if Docker is installed
      stat:
        path: /usr/bin/docker
      register: docker_installeds

    - name: Install required packages for Docker
      package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
        state: present
      when: ansible_pkg_mgr == "apt"

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_pkg_mgr == "apt"

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_pkg_mgr == "apt"

    - name: Install Docker on Ubuntu
      package:
        name: docker-ce
        state: present
      when: ansible_pkg_mgr == "apt"
    
    - name: Install the required Python library for Docker
      pip:
        name: docker
        state: present
        executable: pip3
      when: ansible_pkg_mgr == "apt"

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
    
- name: Build Docker Image
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Build Docker Image
      docker_image:
        name: git-tag-api:0.0.1
        build:
          path: ../../
          pull: no
        source: build
        state: present

    - name: Create temporary directory to save Docker image tarball
      tempfile:
        state: directory
      register: tempdir

    - name: Save Docker Image as a Tarball
      shell: docker save -o {{ tempdir.path }}/git-tag-api-0.0.1.tar git-tag-api:0.0.1

    - name: Copy Docker image tarball to destination directory
      copy:
        src: "{{ tempdir.path }}/git-tag-api-0.0.1.tar"
        dest: /tmp/git-tag-api-0.0.1.tar
        remote_src: yes

- name: Deploy Docker Image
  hosts: all
  become: true

  tasks:
    - name: Copy Docker Image Tarball to Target Hosts
      copy:
        src: /tmp/git-tag-api-0.0.1.tar
        dest: /tmp/git-tag-api-0.0.1.tar

    - name: Load Docker Image on Target Hosts
      shell: docker load -i /tmp/git-tag-api-0.0.1.tar
      become_user: root

    - name: Start Docker Container
      docker_container:
        name: git-tag-api-container
        image: git-tag-api:0.0.1
        state: started
        ports:
          - "3000:3000"

