name: Node.js Docker Build and Run

on:
  push:
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and run Docker container
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

          aws s3 cp s3://evmiguel-config/.env ./.env

          docker build -t tag-api-image .
          docker run -d -p 3000:3000 tag-api-image